name: ci_testing

on:
  push:
    branches:
    - main
    - initial
    - feature/**
  pull_request:
    branches:
    - main

jobs:
  function_health_check_py:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_pyfunctions
        docker-compose ps
    - name: run
      run: make run_health_check_py
    - name: pytest
      run: make test_health_check_py
    - name: black
      run: make black_check_health_check_py
    - name: flake8
      run: make flake8_health_check_py

  function_http_handler_py:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_pyfunctions
        docker-compose ps
    - name: run
      run: make run_http_handler_py
    - name: pytest
      run: make test_http_handler_py
    - name: black
      run: make black_check_http_handler_py
    - name: flake8
      run: make flake8_http_handler_py

  function_instruct_go:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_gofunctions
        docker-compose ps
    - name: test
      run: make instruct_go_docker_test
    - name: build
      run: make instruct_go_docker_build
    - name: run docker
      run: make instruct_go_docker_run_directory
    - name: run local
      run: make instruct_go_local_run_artifact

  function_pass_fail_py:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_pyfunctions
        docker-compose ps
    - name: run
      run: make run_pass_fail_py
    - name: pytest
      run: make test_pass_fail_py
    - name: black
      run: make black_check_pass_fail_py
    - name: flake8
      run: make flake8_pass_fail_py

  terraform_validate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_deployer
        docker-compose ps
    - name: validate
      run: make terraform
