name: ci_testing

on:
  push:
    branches:
    - main
    - initial
    - feature/**
  pull_request:
    branches:
    - main

jobs:
  function_pass_fail_py:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_pyfunctions
        docker-compose ps
    - name: run
      run: make run_pass_fail_py
    - name: pytest
      run: make test_pass_fail_py
    - name: black
      run: make black_check_pass_fail_py
    - name: flake8
      run: make flake8_pass_fail_py

  terraform_validate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        make ci_build_deployer
        docker-compose ps
    - name: validate
      run: make terraform
